#lang racket
(require "TDA_option.rkt")
(require "TDA_flow.rkt")
(require "TDA_chatbot.rkt")
(require "TDA_system.rkt")

#|
(define op1 (option 1 "Viajar" 2 4 "viajar" "turistear" "conocer"))
(define op2 (option 2 "vuelo" 2 4 "viajar" "turistear" "conocer"))
(define op3 (option 3 "Taxi" 2 4 "viajar" "turistear" "conocer"))
(define op4 (option 5 "Taxi" 2 4 "viajar" "turistear" "conocer"))

(define f9 (flow 1 "Flujox"))
(define f10 (flow 1 "Flujo1" op1 op2 op2 op1 op3))
(define f12 (flow 1 "Flujo2" op1 ))
(define f11 (flow-add-option f10 op4))
(define f13 (flow 2 "Flujo3" op3))
(define chatbot1 (chatbot 1 "chatbot1" "Hola" f10 f12))
(define cb10 (chatbot 0 "“Asistente”" "“Bienvenido\n¿Qué te gustaría hacer?”" 2))
(define cb11 (chatbot 1 "“Asistente”" "“Bienvenido\n¿Qué te gustaría hacer?”" 1 f12))
(define s0 (system "“NewSystem”" 0))
(define s1 (system" “NewSystem”" 0 cb11 cb10))
(define s2 (system-add-user s1 "“user0”"))
(define s3 (system-add-user s2 "“user1”"))
(define s4 (system-login s3 "“user1”"))
(define s5 (system-login s4 "“user0”"))
|#
(define op1 (option  1 "1) Viajar" 2 4 "viajar" "turistear" "conocer") )
(define op2 (option  2 "“2) Estudiar”" 4 3 "“aprender”" "“perfeccionarme”") )
(define f10 (flow 1 "“Flujo1: mensaje de prueba”"))
(define f12 (flow 1 "“Flujo1: mensaje de prueba”" op1 op2))
(define f11 (flow-add-option f10 op1))
(define f13 (flow-add-option f11 op2))
(define cb10 (chatbot 0 "“Asistente”" "“Bienvenido\n¿Qué te gustaría hacer?”" 1))
(define cb11  (chatbot 0 "“Asistente”" "“Bienvenido\n¿Qué te gustaría hacer?”"  1 f12))
(define cb12 (chatbot-add-flow cb10 f12))
(define s0 (system "“NewSystem”" 0))
(define s1 (system "“NewSystem” " 0 cb11))
(define s1000000 (system-add-chatbot s0 cb11))
(define s2 (system-add-user s1 "“user0”"))
(define s3 (system-add-user s2 "“user1”"))
(define s4 (system-login s3 "“user0”"))
(define s1000 (system-logout s4))